name: test-pyhton-algorithms
on: [push]
jobs:
  check-test:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd ./01-MST/
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute tests
      env:
        PYTHONPATH: "../"
      run: |
        cd ./01-MST/tests/
        python -m unittest discover -p 'test_*.py'
  type-checking:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install mypy

    - name: Execute type checking
      run: mypy .