name: static-type-check
on: [push]
jobs:
  type-check:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install mypy

    - name: Execute type checking
      run: mypy *